### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by hossein-kshvrz** [phessabi/eshop#3]
**Is your feature request related to a problem? Please describe.**
Yes. Some of my products are not sold very well.

**Describe the solution you'd like**
I would like to offer discounts for my products on your website.

**Comment by phessabi** [comment]
Dear @hossein-kshvrz, 

Our development team is currently working on adding a "Campaign" feature for vendors which makes offerings and discounting possible.

thanks for your suggestion
